services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deployer
    container_name: svelte-app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=/api
    networks:
      - shared-net
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - svelte-app
    networks:
      - shared-net

volumes:
  caddy_data:
  caddy_config:

networks:
  shared-net:
    external: true

